name: CI/CD for Users Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'lambda_functions/lambda_users/**'
      - 'app/**'
      - 'app/tests/**'

jobs:
  CI:
    name: CI - Run Tests for Users Lambda
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mangum
          pip install pytest

      - name: Run Tests
        run: |
          pytest tests/ --maxfail=5 --disable-warnings

  CD:
    name: CD - Deploy Users Lambda
    needs: CI  # Este job solo se ejecuta si el job 'ci' pasa
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mangum

      - name: Zip Lambda function
        run: |
          zip -r lambda_users_package.zip lambda_functions/lambda_users/ app/ -x "*.pyc" "__pycache__/*"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Lambda to AWS
        run: |
          aws lambda update-function-code --function-name my-users-lambda --zip-file fileb://lambda_users_package.zip
