name: CI/CD for Auth Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'lambda_functions/lambda_auth/**'
      - 'app/**'
      - 'app/tests/**'

jobs:
  CI:
    name: CI - Run Tests for Auth Lambda
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m venv lambda_functions/lambda_auth/venv
          source lambda_functions/lambda_auth/venv/bin/activate
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          source lambda_functions/lambda_auth/venv/bin/activate
          pytest

  CD:
    name: CD - Deploy Auth Lambda
    needs: CI  # Este job solo se ejecuta si el job 'ci' pasa
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv lambda_functions/lambda_auth/venv
          ls
          source lambda_functions/lambda_auth/venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install mangum

      - name: Zip Lambda function
        run: |
          cd lambda_functions/lambda_auth
          zip -r ../../lambda_auth_package.zip . -x "*.pyc" "__pycache__/*"
          cd ../..

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Lambda to AWS
        run: |
          aws lambda update-function-code --function-name auth-lambda --zip-file fileb://lambda_auth_package.zip
